### ISSUE TITLE
implement(kafka): implement a layer of services to allow connection to kafka

### ISSUE THREAD

**Issue by thewilly** [Arquisoft/InciManager_i3a#22]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the motivation / use case for changing the behavior?

For the other modules to be able to send data to kafka streamline it will be compulsory a layer of services for interconnection with kafka. This layer should provide a public interface for others to connect with it.

**Comment by ByBordex** [comment]
PR #32
