### ISSUE TITLE
Exception when executing the method sendKafka from the web service

### ISSUE THREAD

**Issue by CarlosGarciaHdez** [Arquisoft/InciManager_i3a#39]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

The method is expecting the values login and password that the web service doesn´t provide, resulting in a null pointer exception when calling toString method for that value. Also, some values of the form in the web service are optional and can be null in the payload, so it has to take it into account.

## What is the motivation / use case for changing the behavior?

Others:

</code></pre>

**Comment by ByBordex** [comment]
Working on it.

**Comment by ByBordex** [comment]
@CarlosGarciaHdez The error seems to be caused by the lack of parameters login and password, you should provide them(Read document for 2nd deliverable), you may save those values when using the login in some kind of HttpSession and then get them in the setIncident().

Regarding optional fields i'm gonna improve the implementation to avoid null pointers in them.

**Comment by thewilly** [comment]
From the documentation file: _Each incident can have the following fields: **user name and password**, incident name, description, location (which will be automatically obtained if possible), tags (list of words separated by commas that will allow to categorize incidents), additional information (pictures, videos, etc). For some incidents, a list of fields can also be added with the form "property/value", where the property field refers to a property name and the value field refers to the value of that property._ 

_If the combination "user name/password" is not right, incidents will not be processed and an error will be reported. If the combination is right, incidents will be processed and the processed incident will be submitted to Apache Kafka for its further handling by module 4 (InciDashboard)._

Given those two paragraphs is clear that the user and the password are used just to check if the agent has authority to login and send the incidence. There's no need to send them with the incident, besides sending the password is like killing the security. If you want, and i think it's a good idea is to submit a reference to the agent that created the incident, its login and kind are enough.

**Comment by thewilly** [comment]
@ByBordex why if there's no password you do not save the incidene? the login has been already checked at that point.

**Comment by ByBordex** [comment]
Discussed at #44 solved in #41
