### ISSUE TITLE
Kafka services not inserting data if some conditions are not fulfilled

### ISSUE THREAD

**Issue by thewilly** [Arquisoft/InciManager_i3a#44]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When trying to insert an incidence form a user it does not work if the no passing username, password, incidence name, description or location.

```java
if( payload.get("login") == null )
    return false;
if( payload.get("password") == null )
    return false;
if( payload.get("incidenceName") == null )
    return false;
if( payload.get("description") == null )
    return false;
if( payload.get("location") == null )
    return false;
```

## Expected behavior

An incidence should be stored only with its "value" that does not include not username nor password, at most a reference to the agent that created the incidence but never the password.
From there, not all the incidences will have a description nor a location, in the system the incidences **may** have those values but don't must.

**Comment by ByBordex** [comment]
Will fix, password, description and location fields will not be checked, however login will as you mention it will be used as a reference for the agent.

**Comment by thewilly** [comment]
Awesome thanks
