### ISSUE TITLE
Kafka service not working on production environment

### ISSUE THREAD

**Issue by thewilly** [Arquisoft/InciManager_i3a#46]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

The kafka service does not get connection from cloudkarafka in production environment. So when sending data to this service the system always fails.

## Expected behavior

That the kafka services connect properly to cloudkarafka so the application does not fail when sending data to this service.

**Comment by ByBordex** [comment]
It seems that at some points I deleted  **@Configuration** from **KafkaProducerFactory** so it was creating the default template instead of the one desired.

**Comment by thewilly** [comment]
Perfect thanks
