### ISSUE TITLE
Define interface between kafka services and other microservices

### ISSUE THREAD

**Issue by thewilly** [Arquisoft/InciManager_i3a#7]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Description

@ByBordex, to communicate with your kafka service we will need an interface so we do not really rely on your implementation, so i guess it would be something like:
```java
    sendIncidence(String json); // A
    sendIncidence(JSONNode json); // B
```
Then, my question is which type of object are you going to ask for, option A or something like B?

**Comment by thewilly** [comment]
Maybe even a HashMap that is a data structure all we control perfectly, its a build in collection and has an iterable?

**Comment by ByBordex** [comment]
I believe the HashMap option would be the best one.

**Comment by thewilly** [comment]
Perfect! cannot wait to see your interface!

**Comment by thewilly** [comment]
Please make the public interface to return a boolean that contains if the insertion/send to MongoDB/Kafka was successful.

Something like this would be awesome.
```java
public interface AwesomeInterface {
   
   /**
    * Sends a payload map to the Kafka stream pipe and stores in mongoDB for
    * redundancy.
    *
    * @return true if the Kafka and mongoDB insertions where right. False otherwise.
    *
    * @param payload is the map of key type string and value type object that
    * will represent the JSON of the request. The Object value type helps not to bound
    * the value to only one type.
    */
    boolean send(Map<String, Object> payload);
}
```
